spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.188.130:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.188.130
    port: 6379

server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d" - "%msg%n"
#  path:
projectUrl:
  sell: 127.0.0.1:8080
